def DNA(nts):
    """Counting DNA Nucleotides"""
    ntsDict = {}
    for nt in nts:
        if nt in ntsDict:
            ntsDict[nt] += 1
        else:
            ntsDict[nt] = 1
    return ntsDict

if __name__ == "__main__":
    ntsDict = DNA('CCTCTTTCATGTCCAATTTAATATTAGATAACACGTGGTGAAACCACGTTTACGCCACATGATCGTGGTTCACAATTTAGTTCGTGTTCGGAGTCATCAGGCTCATCGTAGTTAAGGGCCGTCCTATTCATTTGACTTTTGTTTAGACTTTCTATTACGAATCGGTGCTTATTCTAAGAGCAAGTTACTCCGAACCAACCATTCCTAAGGGGCCTTAGTCGGTAGTTAGGTTGTCCCTAGCACTCGTATACCCCCTTGGCGTTCTGTCGGGTTGTAGGAGTCAGTCGCACGGGTTTTGATACGAGGCGGTGGCAGGAAATCGGACTGCTAACCTTGCTATAGCAAGAGTTTGCGGCTACTATTCGCAACAGAGAATTTTGCTTGGAGATCTTTAAGAGAAGCAAACTTGACCATACCTCAAACTTTCCCCCTGGAATTAGGGTACCAGGGCTACCGATTTCATGAATAAATGTATACAATACGCCGTCAAGGGTGATGGGGAATAGCAACCGCCAGTGGGCACAACTGCAGCCTCAACGCAACTCATGTGTTAATTTCCGCCGTGCCATTCCCGCGACATTCTGCGATTCTTTTTGAGCGGGGTCTGATACTACCATACTGATCTAGCACTGGTCACCCCTGGGTTTGAGAGCCAGTAGTTCGTGGTCATTGTTGACTCGGCGTCCACGGATCGGTTCCGGTGGTCATCGATGATTGGTTAGTGGACGTTACTTCTATGGTGTTGGACCTATCTTGCTACAGGATGAGTGCTTACGGGCACTGCAGTCTCTTTTTCATTCTCTGAAAAAGTGGCCCCGATTTT')
    print('{0} {1} {2} {3}'.format(ntsDict['A'], ntsDict['C'], ntsDict['G'], ntsDict['T']))
        