def RNA(nts):
    """Transcribing DNA into RNA"""
    rna = ""
    for nt in nts:
        if nt is 'T':
            rna += 'U'
        else:
            rna += nt
    return rna

if __name__ == "__main__":
    print(RNA("CTGGAGTTCCTTTCACTTCGACTGTTCGGCAGTCGTTGCGGGGTCATGTAATACTTGGCAGCCAAACGCGGTGGCTACGCGCAAGTCCGGTGATACCCAGGTAACATAGATCTGTTGCTACACGGATCACCGTGTGAAAGAACCAGCCCAAAACCTAACCGTATGGTACTCGCGCTGTAGTACCTCGGTTGTAATTTCTATCTCTACAATGCCTGTGCGCGTAGGCGCGTCTCAATCACCAACTGACCTAGAGTCAGTCCAGTAAAGTTGGAGGGTAAGTATTCGCTCATACCTAGGGCCAGCTAGGAGTAGGGGATAGGAATGCAGAACAAATCGCGACCGAGCCATCAAATCTTGCCCTACGGCAGCGGCACCAAAACCTTGAAACACCGGACAAGGCCCCTGACTAGACCGTACATATGTACATTATCATCGCCGAGTTAACGTAAATATTGCGCGTTGCCCCTAGAGAAATCATGCGCCGATAGAAAAGTTCAAGCACGGCCCTTTTCAGGTCCTTGCGATCCGTTTCAGGTCTAACATTTATGAGGGGTTCTATCCCCCGAGTTTTGTGTCGGTGTATTGGTCTAACCTCACCGGGTTGATGAGTTCATAGTTCTGGACGGTACAGCCATAATCGATTATGTTCGCGTGCTCTGTACAGTCATAGAGTCCAAGCGGATTCGATTCTTATTAACCGGCCAGCTGTTCAAGGGAGTCGGGAAAAGGATGTCATTAAACGGCTCAGTCTCAGAACCGTGCCGGGTTCAACAACGCAAACAAAGTGGGCGCGGCTCCCGTCCGTAAACGAGGACTTTACCAACTAGCTTCGTCGTCGCTTCTAGACGCTTTCAGACGAATTGAATAACAGCCAGTATCTCGACAGGATAAAAAGAGTTGGTCATCAGTATTGATGGCCATCTGCATGCGTTGAGACCTGTCTCAGGATGGCCATAACTCACTGCG"))